<?php

namespace CompBundle\Repository;

/**
 * aimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aimeRepository extends \Doctrine\ORM\EntityRepository
{
}
