<?php

namespace CompBundle\Repository;
use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;
use CompBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findPostBYId($id){
        return $this->getEntityManager()
            ->createQuery("SELECT p FROM CompBundle:Post p WHERE p.id = :id")
            ->setParameter('id',$id)
            ->getOneOrNullResult();
    }
}
