<?php

namespace CompBundle\Repository;
use \Doctrine\ORM\EntityRepository;



use CompBundle\Entity\Postcomment;
use CompBundle\Entity\Post;
/**
 * PostcommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * get post postcomment
 *
 * @param integer $post_id
 *
 * @return array
 */
class PostcommentRepository extends EntityRepository
{
    public function getPostComments($post_id){
        return $this->getEntityManager()
            ->createQuery("SELECT c, u.username From CompBundle:Postcomment c JOIN c.user u WHERE c.post = :id")
            ->setParameter('id',$post_id)
            ->getArrayResult();
    }

}
