<?php

namespace CompBundle\Repository;

use CompBundle\Entity\Postcomments;
use Doctrine\ORM\Mapping;
use Symfony\Component\EventDispatcher\Tests\Service;

/**
 * PostcommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostcommentsRepository extends \Doctrine\ORM\EntityRepository
{
}
