<?php

namespace CompBundle\Repository;

/**
 * Sponsors_CompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sponsors_CompetitionRepository extends \Doctrine\ORM\EntityRepository
{
}
